In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("Loan.csv")

In [3]:
df.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [9]:
df.head()

no_of_dependents      education self_employed  income_annum  loan_amount  \
0                 2       Graduate            No       9600000     29900000   
1                 0   Not Graduate           Yes       4100000     12200000   
2                 3       Graduate            No       9100000     29700000   
3                 3       Graduate            No       8200000     30700000   
4                 5   Not Graduate           Yes       9800000     24200000   

   loan_term  cibil_score  residential_assets_value  commercial_assets_value  \
0         12          778                   2400000                 17600000   
1          8          417                   2700000                  2200000   
2         20          506                   7100000                  4500000   
3          8          467                  18200000                  3300000   
4         20          382                  12400000                  8200000   

   luxury_assets_value  bank_asset_value  loan_status  
0             22700000           8000000            1  
1              8800000           3300000            0  
2             33300000          12800000            0  
3             23300000           7900000            0  
4             29400000           5000000            0

In [10]:
df.education.replace({" Not Graduate": 'Not Graduate', " Graduate": "Graduate"}, inplace=True)  

C:\Users\Prashant Dhoju\AppData\Local\Temp\ipykernel_7972\1855028086.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.education.replace({" Not Graduate": 'Not Graduate', " Graduate": "Graduate"}, inplace=True)


In [11]:
df.self_employed.replace({" No": 'No', " Yes": "Yes"}, inplace=True)        

C:\Users\Prashant Dhoju\AppData\Local\Temp\ipykernel_7972\4060097925.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.self_employed.replace({" No": 'No', " Yes": "Yes"}, inplace=True)


In [12]:
print(df.iloc[0, :])

no_of_dependents                   2
education                   Graduate
self_employed                     No
income_annum                 9600000
loan_amount                 29900000
loan_term                         12
cibil_score                      778
residential_assets_value     2400000
commercial_assets_value     17600000
luxury_assets_value         22700000
bank_asset_value             8000000
loan_status                        1
Name: 0, dtype: object


In [13]:
X = df.drop(columns=['loan_status'])
y = df.loan_status

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
transformer = ColumnTransformer(
    [
        ('trnf', OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore'), [1, 2])
    ], remainder='passthrough'
)

pipe = Pipeline([
    ('transformer', transformer),
    ('Model', RandomForestClassifier(n_estimators=20))
])

In [16]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trnf',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 2])])),
                ('Model', RandomForestClassifier(n_estimators=20))])

In [17]:
y_pred = pipe.predict(X_test)

In [18]:
accuracy_score(y_test, y_pred)

0.9765807962529274

In [19]:
import pickle

In [20]:
pickle.dump(pipe, open('pipe.pkl', 'wb'))

In [21]:
df.head()

no_of_dependents     education self_employed  income_annum  loan_amount  \
0                 2      Graduate            No       9600000     29900000   
1                 0  Not Graduate           Yes       4100000     12200000   
2                 3      Graduate            No       9100000     29700000   
3                 3      Graduate            No       8200000     30700000   
4                 5  Not Graduate           Yes       9800000     24200000   

   loan_term  cibil_score  residential_assets_value  commercial_assets_value  \
0         12          778                   2400000                 17600000   
1          8          417                   2700000                  2200000   
2         20          506                   7100000                  4500000   
3          8          467                  18200000                  3300000   
4         20          382                  12400000                  8200000   

   luxury_assets_value  bank_asset_value  loan_status  
0             22700000           8000000            1  
1              8800000           3300000            0  
2             33300000          12800000            0  
3             23300000           7900000            0  
4             29400000           5000000            0

In [22]:
df.education[0]

'Graduate'

In [23]:
model = pickle.load(open('pipe.pkl', 'rb'))

In [24]:
value = np.array([2, 'Graduate', 'No', 6000, 7000, 8000, 4000, 3000, 7000, 5000, 400],dtype=object).reshape(1,11)


In [25]:
value

array([[2, 'Graduate', 'No', 6000, 7000, 8000, 4000, 3000, 7000, 5000,
        400]], dtype=object)

In [26]:
df.iloc[0:1, :11]

no_of_dependents education self_employed  income_annum  loan_amount  \
0                 2  Graduate            No       9600000     29900000   

   loan_term  cibil_score  residential_assets_value  commercial_assets_value  \
0         12          778                   2400000                 17600000   

   luxury_assets_value  bank_asset_value  
0             22700000           8000000

In [27]:
df.iloc[0:1, :11].values

array([[2, 'Graduate', 'No', 9600000, 29900000, 12, 778, 2400000,
        17600000, 22700000, 8000000]], dtype=object)

In [28]:
df.iloc[0]

no_of_dependents                   2
education                   Graduate
self_employed                     No
income_annum                 9600000
loan_amount                 29900000
loan_term                         12
cibil_score                      778
residential_assets_value     2400000
commercial_assets_value     17600000
luxury_assets_value         22700000
bank_asset_value             8000000
loan_status                        1
Name: 0, dtype: object

In [29]:
model.predict(df.iloc[0:1, :11])

array([1])

In [30]:
model.predict(value)

c:\Users\Prashant Dhoju\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([0])

In [31]:
new_val = [34, 'Not Graduate', 'Yes', 23542534, 345425234, 12, 345, 4535345, 5345345, 355345, 35435345]

In [32]:
import numpy as np

In [33]:
a = np.array(new_val).reshape(1,11)

In [34]:
model.predict(a)

c:\Users\Prashant Dhoju\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([0])

In [1]:
import tensorflow as tf

print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
print("GPU Details:", tf.config.list_physical_devices('GPU'))


ModuleNotFoundError: No module named 'tensorflow'

In [2]:
!pip install tensorflow

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for tensorflow


In [3]:
import pytorch as pt

ModuleNotFoundError: No module named 'pytorch'

  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Failed to build pytorch


  error: subprocess-exited-with-error
  
  × Building wheel for pytorch (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Prashant Dhoju\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\Prashant Dhoju\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Prashant Dhoju\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ~~~~~~~~~~~~~~~~~